### ISSUE TITLE
Data format of IMU and GPS in .csv

### ISSUE THREAD

**Issue by RonghaiHe** [ORCA-TECH/USVInland-Dataset#4]
The datasets are comprehensive, however there is a question. I wonder what the data format is in the IMU_inside_camera.csv in the document of SLAMOdometry? so as the GPSRover.csv.

**Comment by RonghaiHe** [comment]
I found README.md in the document of the USVInland_SLAM_SDK_1.0.1, which had been neglected before because of my carelessness. Now I close this issue.

**Comment by kaansahin-As** [comment]
I could not find USVInland_SLAM_SDK. Is there any access link or something? @RonghaiHe
